language: android

sudo: false

cache:
  directories:
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

  - sdkmanager tools
  - sdkmanager "system-images;android-18;default;armeabi-v7a"
#  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
#  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

before_script:
#  - android-wait-for-emulator
#  - adb shell input keyevent 82

script:
  - ./gradlew test

after_success:
#  - script/deploy_apk.sh

env:

branches:
  except:
    - gh-pages

notifications:
  email: false